language: cpp
os: linux
compiler:
  - g++-7
  - clang++-6.0

jobs:
  include:
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - gcc-7
      - clang++-6.0

install: 
  - sudo ./INSTALL.sh
  
script:
  - make

notifications:
  email:
    recipients:
      - d3psigames@gmail.com
    on_success: always
    on_failure: always