language: cpp
os: linux

jobs:
  include:
    - os: linux
      dist: xenial
      compiler: g++-7
    - os: linux
      dist: bionic
      compiler: g++-7
    - os: linux
      dist: xenial
      compiler: clang++-6.0
    - os: linux
      dist: bionic
      compiler: clang++-6.0

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - gcc-7
      - clang++-6.0

install: 
  - sudo ./INSTALL.sh
  
script:
  - make

notifications:
  email:
    recipients:
      - d3psigames@gmail.com
    on_success: always
    on_failure: always