version: 2

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: ./INSTALL.sh --no-build
      - run:
          name: Build
          command: make
