name: C/C++ CI

on: [push, pull_request]

jobs:
 build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-18.04, ubuntu-latest ]
        compiler: [ g++, clang++ ]
    name: ${{ matrix.compiler }} compilation on ${{ matrix.os }} 
    steps:
     - name: Checkout code
       uses: actions/checkout@master
     - name: Install dependencies
       run: sudo ./INSTALL.sh --no-build
     - name: Build
       run: make
